services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    depends_on:
      - database
    networks:
      - miniamaker_network

  nginx:
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
      - php
    networks:
      - miniamaker_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: miniamaker_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: miniamaker_db
      PMA_PORT: 3306
    depends_on:
      - database
    networks:
      - miniamaker_network

  database:
    image: mysql:latest
    container_name: miniamaker_db
    restart: always
    environment:
      MYSQL_DATABASE: miniamaker_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - miniamaker_db:/var/lib/mysql:rw
    networks:
      - miniamaker_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"  # Interface web
      - "1025:1025"  # Serveur SMTP
    restart: unless-stopped
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - miniamaker_network

networks:
  miniamaker_network:

volumes:
  miniamaker_db: